In [7]:
from pathlib import Path
import pandas as pd

root = Path.cwd()
csv_dir = (root / "data" / "raw") if (root / "data" / "raw").exists() else (root.parent / "data" / "raw")

files = sorted(csv_dir.glob("*.csv"))
print("CSV em:", csv_dir, "->", [f.name for f in files])
assert files, f"sem CSV em {csv_dir}"

df = pd.read_csv(files[0])
df.shape, df.columns.tolist()

CSV em: c:\Users\marce\OneDrive\Documentos\Projetos\indicium_ds_challenge\data\raw -> ['desafio_indicium_imdb.csv']

((999, 16),
 ['Unnamed: 0',
  'Series_Title',
  'Released_Year',
  'Certificate',
  'Runtime',
  'Genre',
  'IMDB_Rating',
  'Overview',
  'Meta_score',
  'Director',
  'Star1',
  'Star2',
  'Star3',
  'Star4',
  'No_of_Votes',
  'Gross'])

In [8]:
df.head(10)

,Unnamed: 0,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
1,2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
2,3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
3,4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
4,5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
5,6,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
6,7,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
7,8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
8,9,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,"315,544,750"

In [9]:
df.dtypes

Unnamed: 0         int64
Series_Title      object
Released_Year     object
Certificate       object
Runtime           object
Genre             object
IMDB_Rating      float64
Overview          object
Meta_score       float64
Director          object
Star1             object
Star2             object
Star3             object
Star4             object
No_of_Votes        int64
Gross             object
dtype: object

In [10]:
df.isna().sum().sort_values(ascending=False)

Gross            169
Meta_score       157
Certificate      101
Unnamed: 0         0
Runtime            0
Genre              0
Series_Title       0
Released_Year      0
Overview           0
IMDB_Rating        0
Star1              0
Director           0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
dtype: int64

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,999.0,NaN,NaN,NaN,500.0,288.530761,1.0,250.5,500.0,749.5,999.0
Series_Title,999,998,Drishyam,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Released_Year,999,100,2014,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Certificate,898,16,U,234,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Runtime,999,140,100 min,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genre,999,202,Drama,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IMDB_Rating,999.0,NaN,NaN,NaN,7.947948,0.27229,7.6,7.7,7.9,8.1,9.2
Overview,999,999,An organized crime dynasty's aging patriarch t...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Meta_score,842.0,NaN,NaN,NaN,77.969121,12.383257,28.0,70.0,79.0,87.0,100.0
Director,999,548,Alfred Hitchcock,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star1,999,659,Tom Hanks,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star2,999,840,Emma Watson,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star3,999,890,Rupert Grint,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star4,999,938,Michael Caine,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
No_of_Votes,999.0,NaN,NaN,NaN,271621.422422,320912.621055,25088.0,55471.5,138356.0,373167.5,2303232.0
Gross,830,822,"4,360,000",5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
import numpy as np

if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])

df["Released_Year"] = pd.to_numeric(df["Released_Year"], errors="coerce")
df["Meta_score"] = pd.to_numeric(df["Meta_score"], errors="coerce")
df["No_of_Votes"] = pd.to_numeric(df["No_of_Votes"], errors="coerce")
df["Runtime_min"] = (df["Runtime"].astype(str).str.extract(r"(\d+)")[0].astype(float))
df["Gross_usd"] = (df["Gross"].astype(str).str.replace("[,$]", "", regex=True).replace("nan", np.nan))
df["Gross_usd"] = pd.to_numeric(df["Gross_usd"], errors="coerce")
    
df.shape, df.dtypes.loc[["Released_Year", "Meta_score", "No_of_Votes", "Runtime_min", "Gross_usd"]]

((999, 17),
 Released_Year    float64
 Meta_score       float64
 No_of_Votes        int64
 Runtime_min      float64
 Gross_usd        float64
 dtype: object)

In [ ]:
try:
    import sklearn
except ImportError:
    %pip install scikit-learn -q

from sklearn.model_selection import train_test_split
import numpy as np

y = df["IMDB_Rating"].astype(float)
X = df.drop(columns=["IMDB_Rating"])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

y_pred = np.repeat(y_train.mean(), len(y_val))

rmse = np.sqrt(((y_val - y_pred) ** 2).mean())
mae = np.abs(y_val - y_pred).mean()
rmse, mae

(np.float64(0.25680367823287314), np.float64(0.21162953692115138))

In [21]:
try:
    import sklearn
except ImportError:
    %pip install scikit-learn -q

from pathlib import Path
import sys, importlib
sys.path.insert(0, str(Path.cwd().parent))

from src.data import load_clean
import src.model as mdl
importlib.reload(mdl)

df = load_clean()
rmse, mae, pipe = mdl.train_validate(df)
rmse, mae

(0.20166515152952577, 0.1609207301805563)

In [22]:
from pathlib import Path
import joblib

Path("models").mkdir(exist_ok=True)
joblib.dump(pipe, "models/imdb_ridge.pkl")

['models/imdb_ridge.pkl']